//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashRegister.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CashRegister.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred while generating CashDictionary:.
        /// </summary>
        internal static string ErrorGeneratingCashDictionary {
            get {
                return ResourceManager.GetString("ErrorGeneratingCashDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred while randomizing CashDictionary:.
        /// </summary>
        internal static string ErrorRandomizingCashDictionary {
            get {
                return ResourceManager.GetString("ErrorRandomizingCashDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred while selecting Input File:.
        /// </summary>
        internal static string ErrorSelectingInputFile {
            get {
                return ResourceManager.GetString("ErrorSelectingInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred while setting control properties: .
        /// </summary>
        internal static string ErrorSettingControlProperties {
            get {
                return ResourceManager.GetString("ErrorSettingControlProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred while executing ReplaceWithPlurals method:.
        /// </summary>
        internal static string ErrorWhenApplyingReplaceWithPlurals {
            get {
                return ResourceManager.GetString("ErrorWhenApplyingReplaceWithPlurals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred while clicking About Cash Register link:.
        /// </summary>
        internal static string ErrorWhenClickingAboutLabel {
            get {
                return ResourceManager.GetString("ErrorWhenClickingAboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred while closing the About form:.
        /// </summary>
        internal static string ErrorWhenClosingAboutForm {
            get {
                return ResourceManager.GetString("ErrorWhenClosingAboutForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred while executing ErrorWhenExecutingGetMonetaryDenominationsDue method:.
        /// </summary>
        internal static string ErrorWhenExecutingGetMonetaryDenominationsDue {
            get {
                return ResourceManager.GetString("ErrorWhenExecutingGetMonetaryDenominationsDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred while executing OutputChangeToCustomer method:.
        /// </summary>
        internal static string ErrorWhenExecutingOutputChangeToCustomer {
            get {
                return ResourceManager.GetString("ErrorWhenExecutingOutputChangeToCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred while exiting the application:.
        /// </summary>
        internal static string ErrorWhileExitingApplication {
            get {
                return ResourceManager.GetString("ErrorWhileExitingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred while resetting fields: .
        /// </summary>
        internal static string ErrorWhileResettingFields {
            get {
                return ResourceManager.GetString("ErrorWhileResettingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred while running process to download output file: .
        /// </summary>
        internal static string ErrorWhileRunningProccessToDownloadOutputFile {
            get {
                return ResourceManager.GetString("ErrorWhileRunningProccessToDownloadOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Cash Register! Please begin by pressing the ‘Open’ button and selecting a flat input file from your computer. It is expected that this file will contain one to many lines of data. Valid entries in the file will contain two decimal amounts separated by a comma. The first entry will represent total amount due and the second will represent the amount paid by the customer. The contents of the input file will be displayed for your reference in the textbox labeled ‘Contents of Input File.’ After al [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProgramInformation {
            get {
                return ResourceManager.GetString("ProgramInformation", resourceCulture);
            }
        }
    }
}
